# Generated by Django 4.2 on 2023-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='fonte',
            field=models.CharField(default='sem fonte', max_length=150),
            preserve_default=False,
        ),
    ]
