# Generated by Django 4.2 on 2023-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_alter_commands_cover_alter_commands_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='slag',
            field=models.SlugField(unique=True),
        ),
    ]
